Adds feature for filtering annotations by shapes and user in Largo
biigle/largo pull request #193
Opened 2024-10-31 11:00 UTC by dbrembilla

This PR (partially) addresses issue #66 by introducing a filtering tab in Largo for users and shapes.
I also introduced tests for the new filtering functionalities on the backend side.

What I hoped to achieve, was a system that could be expanded upon. Please let me know if this is satisfactory.
Something that I am not 100% convinced is the fact that the filters get loaded on click - I was not able to pass the information from the API in any other way. Is it okay to you? 

To test this, try to use filters to change the displayed largo annotations  and check that no unexpected behaviour is present (e.g. annotations that should not be there that appear, other largo features stop working etc.)

2024-10-31 11:08 UTC, dlangenk commented
Wow. Cool PR. Thanks Davide

2024-11-04 13:48 UTC, mzur requested changes
Awesome, thanks! High-level comments first (in no particular order). I'll look at the code in a later review.

- The BIIGLE modules track their compiled assets (JS/CSS) as well. So once you have something ready to review/publish, please run `npm run prod` once and commit the minified assets. Otherwise you end up with a 4k lines JS file like now.

- When a filter is active, the sidebar tab must be highlighted. Compare this with the sorting tab when a sorting is active:

   ![image](https://github.com/user-attachments/assets/ea6b22d6-f344-47a6-81f5-0452c95e4267)

   This is important so users don't forget about the filters once the tab is closed.

- There is no need to make an API call to fetch the available annotation shapes. You can hard-code them in the template. Either directly as HTML or you populate a JS variable (with `biigle.$declare()` and `biigle.$require()`). Also, if Largo is opened for a single volume and it is not a video volume, the WholeFrame shape should not be shown.

- To make the objective speed faster, you can perform the API call to fetch available users when the filter tab is open (instead of when the select input is focussed). Then the response will hopefully be already there when the user selects the input.

- Ideally, I want the filter tab here to work similar to the filter tab of the volume overview (except the flag/filter switch and the show filenames button):

   ![image](https://github.com/user-attachments/assets/82840288-52ef-4697-84c6-c545b55964db)

   If you want you can implement it this way here. Otherwise we can keep your UI with the select inputs as first version and then update the UI later.


There were two things that didn't work for me:

- When I open Largo for a whole project, I get an empty response from the "users-with-annotations" API endpoint.

- When I click on a label (with annotations) and thenn immediately click on another label (without annotations), it shows the message "no annotations" *for both labels*. I even see a flash of annotation patches of the first label while it loads. But somehow the caching is messed up afterwards. I don't see this behavior in the version on biigle.de so I assume that it has something to do with your changes. Here is an example:

   [Screencast from 04.11.2024 14:42:57.webm](https://github.com/user-attachments/assets/3efa7d7f-447a-4331-8337-33da688c2147)

2024-12-19 11:29 UTC, mzur commented
Is this ready for review again?

2024-12-20 08:43 UTC, dbrembilla commented
> Is this ready for review again?

Yep, should all be okay! @mzur

2024-12-20 08:53 UTC, mzur commented
In the future, please click on "re-request review" here in the UI, otherwise I will ignore what happens here :wink:

2024-12-20 12:57 UTC, mzur requested changes
I didn't dig into the details yet so here are some high-level comments again.

The filtering also doesn't seem to work correctly with videos annotations. I have a couple of point video annotations. When I select "shape is not point", I still see the annotations, both in the volume and project Largo view. In the project view the image annotations are correctly filtered but the video annotations not.

I still see the issue with "no annotations". But with my new faster machine it was harder to reproduce. You can do it by throttling the network connection after Largo was initially loaded:

[Screencast from 2024-12-20 13-51-23.webm](https://github.com/user-attachments/assets/97cf8d93-a377-48fa-bfd4-e9ad489cbbec)

2024-12-20 12:57 UTC, mzur commented on src/Http/Controllers/Views/Projects/LargoController.php
> +        ]);
Use `$shapes = Shape::pluck('name', 'id')` instead. These are database models. The (order of) IDs are not guaranteed to be the same in each application instance.

2024-12-20 12:57 UTC, mzur commented on src/Http/Controllers/Views/Projects/LargoController.php
> +            ->get();
I'd prefer to keep this as an extra API call. If you inject it on every page, the data is always there although not all users will use the filter by user feature. As this is a rather expensive query, we should avoid it unless we need it.

2024-12-20 12:57 UTC, mzur commented on src/Http/Controllers/Views/Volumes/LargoController.php
> +        ];
```suggestion
        $shapes = Shape::pluck('name', 'id')
```

2024-12-20 12:57 UTC, mzur commented on src/Http/Controllers/Views/Volumes/LargoController.php
> +            ->get();
Same than above about the extra API call.

2024-12-20 12:57 UTC, mzur commented on src/resources/views/show/content.blade.php
> +<sidebar-tab :highlight="hasActiveFilters" v-on:disabled="isInRelabelStep" name="filtering" icon="exchange-alt fa-filter fa-solid" title="Filter annotations">
The tab is still highlighted when I remove all filter rules.

2024-12-20 12:57 UTC, mzur commented on src/resources/assets/js/components/filteringTab.vue
> +        this.activeFilters[0].name = this.activeFilters[0].name.substring(
When I remove the last filter rule, I get `this.activeFilters[0] is undefined` in the console.

2024-12-20 12:57 UTC, mzur commented on src/resources/assets/js/components/filteringTab.vue
The tab looks much more similar to the filter tab of the volume overview. What about copying it's style and components to make it look almost the same? This would be best for UX. Would this be too much work? Maybe some logic and components could even be reused.

2025-01-07 09:57 UTC, mzur requested changes
We are getting there, nice work! Filtering with video annotation works now and I also no longer see the "no annotations" bug.

One thing I noticed is that you can mix "and" and "or" filter rules. To keep things simple, in the volume overview, I only allowed to combine all rules either with "and" or with "or". I haven't checked if the boolean logic is correct here (see screenshot) but I feel it is not 😁 At some point we might implement a more sophisticated query/filter system (ref [one](https://github.com/biigle/core/issues/359), [two](https://github.com/biigle/core/issues/241), [three](https://github.com/biigle/core/issues/255#issuecomment-1440004055)) that could be used here, too, but not today.

![Screenshot from 2025-01-07 09-31-07](https://github.com/user-attachments/assets/c2cbd722-9645-45cf-95f9-e26e85d24072)

In the screenshot I also have duplicate identical filter rules. These should be ignored. In the volume overview simply nothing happens if a user wants to add the same filter rule twice. This also results in several identical requests being sent, which could be avoided.

If you implement connecting all rules either with "and" or with "or" you could add this as an additional parameter to the request (e.g. `shape_id[]=7&and=1`), so you can always get the filtered IDs with a single request.

Now to some UI details (on the right there is the volume overview tab for comparison):

![Screenshot from 2025-01-07 09-44-10-edit](https://github.com/user-attachments/assets/f3e74af5-4990-44d9-9086-a96589aa5f40)

1. The "annotations where" can be removed. Also the "and", "or" and "x" buttons need title attributes (see volume filter tab).

2. The select elements are inside `list-group` elements for some reason. This produces an inconsistent margin at the bottom (see white bar in screenshot).

3. To save a little space and make it more consistent with the volume tab, the "is/is not" select can be moved to the top right and the "add filter" button to the bottom right of the select fields. "Add filter" can also be called "add rule" to make it consistent with the volume tab.

4. The list group items have an additional `margin-top` now. This can also be seen in the sorting tab. The margin should be removed.


When the filtering is active, the sorting no longer seems to work correctly (see below).

[Screencast from 2025-01-07 10-45-24.webm](https://github.com/user-attachments/assets/a16bbcfe-c2c9-4f31-8efd-a7e535b3db06)

I only had a quick glance at the code. I'll leave a detailed review for next time.

2025-01-07 09:57 UTC, mzur commented on src/resources/assets/js/components/filteringTab.vue
> +      if ((this.activeFilters.length > 0) & (key == 0)) {
Should this be a `&&` instead?

2025-01-07 09:57 UTC, mzur commented on src/resources/assets/sass/main.scss
Please don't change the indentation, quotation marks etc. here.

2025-01-16 13:48 UTC, dbrembilla commented
@mzur I had forgot to push the last commit. This PR is ready again to be reviewed

2025-01-23 13:48 UTC, mzur requested changes
The UI is great now. I've applied a few final tweaks in 2493cdf.

There is an issue with the sorting. Even if no filter is active, the sorting seems to be random and non-deterministic. If I apply the same sorting multiple times, I get different sorting sequences. Also the selected reference annotation for similarity sorting is included twice:

[Screencast from 2025-01-23 14-43-51.webm](https://github.com/user-attachments/assets/e2c8d42d-d368-4d6f-bc76-e72bf26ed6a7)

Maybe this will be solved with my comment below?

Finally, please update the Largo manual page with a description of the filter tab. use the description of the sorting tab as an example.

Have fun with my detailed comments below :wink:

2025-01-29 09:11 UTC, dbrembilla commented on src/resources/assets/js/components/filteringTab.vue
> +        if (_.some(this.activeFilters, filter)){
I thought that lodash was already present as dependency, that's why I used it. I did not know that the dependencies would end up in the compiled JS file!

2025-01-29 10:14 UTC, mzur commented on src/resources/assets/js/components/filteringTab.vue
> +        if (_.some(this.activeFilters, filter)){
No worries. Before you start to resolve all conversations here: Please leave them unresolved. I need them to check all changes in my next review and will close them myself then :wink:

2025-01-29 11:02 UTC, dbrembilla commented on src/resources/assets/js/components/annotationFilter.vue
> +    let possibleShapes = biigle.$require("largo.availableShapes");
'possibleShapes' is an object, where its keys are the ids  of the shapes and the values are the names. 'activeFilters' is an object that contains the values  of the possible active filters, so that is also an object. 'filterValues' is on an object where the key is the filter identifier and  the value is the object.

2025-01-30 08:45 UTC, dbrembilla commented on tests/Http/Controllers/Api/Projects/GetUsersWithAnnotationsProjectsTest.php
> +        $this->project->addVolumeId($this->imageVolume->id);
Correct me if I'm wrong, but in `ApiTestCase` you create only one user and one volume, right? The point here was to get multiple of these so that we can test the DB when all of them are present. So I'm not sure  how much I can use them here

2025-01-30 09:19 UTC, dbrembilla commented on src/resources/assets/js/components/filteringTab.vue
> +        if (_.some(this.activeFilters, filter)){
Sorry about that! I was  doing so to keep in mind on which I worked

2025-01-31 06:56 UTC, dbrembilla commented on src/resources/assets/js/mixins/largoContainer.vue
> +            )
There used to be when it used to make multiple API calls to get the filtered annotations

2025-01-31 10:47 UTC, dbrembilla commented
d@mzur I had forgot about updating the manual; the PR is ready to be reviewed

2025-02-04 13:52 UTC, mzur requested changes
I replied to some conversations that are still open above. These are shown out of context below (in case you are wondering).

The sorting issue seems to be resolved now, can you confirm that?

I found a new issue. When I "dismiss" an annotation and then activate a filter, the "dismissed" state is no longer shown. When I disable the filter, the state is shown again. This also works the other way around. Whe I activate a filter and dismiss an annotation, the state is no longer shown when the filter is disabled:

[Screencast from 2025-02-04 14-48-14.webm](https://github.com/user-attachments/assets/4f39d54c-2246-4587-af9b-9f808082153f)

2025-02-04 13:52 UTC, mzur commented on src/resources/assets/js/mixins/largoContainer.vue
> +            ) {
```suggestion
            if (this.annotationsCache.hasOwnProperty(cacheKey)) {
```

2025-02-04 13:52 UTC, mzur commented on src/resources/assets/js/mixins/largoContainer.vue
> +                .finally(this.finishLoading);
This looks a little cramped. What about:
```suggestion
                promise1 = this.queryAnnotations(label, requestParams)
                    .then(r => this.gotAnnotations(label, r), handleErrorResponse)
                    .then(a => Vue.set(this.annotationsCache, cacheKey, a))
                    .finally(this.finishLoading);
```

2025-02-04 13:52 UTC, mzur commented on tests/Http/Controllers/Api/Projects/FilterImageAnnotationsByLabelControllerTest.php
> +
While I meant to filter by shapes it also works with users like you did. However, now the comment is misleading (case 6). Please fix this for all four test classes.

2025-02-04 13:52 UTC, mzur commented on tests/Http/Controllers/Api/Projects/GetUsersWithAnnotationsProjectsTest.php
> +        $this->project->addVolumeId($this->imageVolume->id);
You get the "first" project and volume for free from `ApiTestCase`. Of course, if you need more, you have to create them manually. Your current change is exactly what I had in mind, so all is good now :+1:

2025-02-04 13:52 UTC, mzur commented on src/resources/views/manual/tutorials/largo.blade.php
> +            These filters are available today:
```suggestion
            These filters are available:
```

2025-02-04 13:52 UTC, mzur commented on tests/Http/Controllers/Api/Projects/GetUsersWithAnnotationsProjectsTest.php
> +            ['user_id' =>$user2->id, 'firstname' => $user2->firstname, 'lastname' => $user2->lastname]
```suggestion
            ['user_id' => $this->user()->id, 'firstname' => $this->user()->firstname, 'lastname' => $this->user()->lastname],
            ['user_id' => $user2->id, 'firstname' => $user2->firstname, 'lastname' => $user2->lastname]
```

2025-02-04 13:52 UTC, mzur commented on tests/Http/Controllers/Api/Volumes/GetUsersWithAnnotationsVolumesTest.php
> +        $expected = [['user_id' =>$this->user()->id, 'firstname' => $this->user()->firstname, 'lastname' => $this->user()->lastname]];
```suggestion
        $expected = [['user_id' => $this->user()->id, 'firstname' => $this->user()->firstname, 'lastname' => $this->user()->lastname]];
```

2025-02-04 13:52 UTC, mzur commented on tests/Http/Controllers/Api/Volumes/GetUsersWithAnnotationsVolumesTest.php
> +        $expected = [['user_id' =>$user2->id, 'firstname' => $user2->firstname, 'lastname' => $user2->lastname]];
```suggestion
        $expected = [['user_id' => $user2->id, 'firstname' => $user2->firstname, 'lastname' => $user2->lastname]];
```

2025-02-04 13:52 UTC, mzur commented on src/resources/assets/js/mixins/largoContainer.vue
> +            if (!this.selectedLabel){
```suggestion
            if (!this.selectedLabel) {
```

2025-02-04 13:52 UTC, mzur commented on src/resources/assets/js/mixins/largoContainer.vue
> +            if (this.selectedFilters.length > 0){
```suggestion
            if (this.selectedFilters.length > 0) {
```

2025-02-04 13:52 UTC, mzur commented on src/resources/views/show/content.blade.php
> +</sidebar-tab>
Please fix the indentation.

2025-02-05 06:04 UTC, dbrembilla commented on src/Http/Controllers/Api/Projects/FilterVideoAnnotationsByLabelController.php
Terribly sorry about that, I was convinced I changed them. I will fix it soon.

2025-02-12 10:55 UTC, dbrembilla commented
> The UI is great now. I've applied a few final tweaks in [2493cdf](https://github.com/biigle/largo/commit/2493cdf2e8d724e62d24d7266c7a9826a1bd4fd5).
> 
> There is an issue with the sorting. Even if no filter is active, the sorting seems to be random and non-deterministic. If I apply the same sorting multiple times, I get different sorting sequences. Also the selected reference annotation for similarity sorting is included twice:
> Screencast.from.2025-01-23.14-43-51.webm
> 
> Maybe this will be solved with my [comment below](https://github.com/biigle/largo/pull/193#discussion_r1926937102)?
> 
> Finally, please update the Largo manual page with a description of the filter tab. use the description of the sorting tab as an example.
> 
> Have fun with my detailed comments below 😉

Hi @mzur, yes the sorting should be okay now. Actually, I realized that I was approaching the filtering the wrong way, since  adding the new data to the `annotationsCache` was causing duplication of data and this problem of information that ended up being lost when changing the filters. Now this should be okay

2025-03-06 10:31 UTC, mzur requested changes
When I go to the "relabel" step, the filter remains active but has no effect. We can either disable the filter tab (as with the sorting) or reset the filter rules and allow the user to enable a new filter that works for the relabel step. In this case, if the user goes back to "dismiss", the filter rules should be reset again, too. What do you think?

[Screencast from 2025-03-06 10-02-49.webm](https://github.com/user-attachments/assets/a72f7d15-ca48-4681-b9ec-755ca65e772d)

Also I saw lots of JS lines that weren't termiated with a `;`. While this is optional in JS, you should adhere to the coding style of this project and add them. Coding style is important in a larger project with multiple collaborators, so please watch your spaces and semicolons in the future 😉

2025-03-06 10:31 UTC, mzur commented on src/resources/assets/js/mixins/largoContainer.vue
> +                    annotations = annotations.filter(annotation => this.filtersCache[filtersCacheKey].includes(annotation.id));
This looks a little inefficient, since `includes()` could traverse the whole array each time. What about adding an object/map instead of an array to `filtersCache` when it is populated (`{id: true}`)? Then you could do O(1) lookups here (`this.filtersCache[filtersCacheKey][annotation.id] === true`).

I'm a little sensitive about performance here because you can have hundreds of thousands of annotations in Largo.

2025-03-06 10:31 UTC, mzur commented on src/resources/assets/js/mixins/largoContainer.vue
> +            return this.selectedLabel && !this.loading && this.sortedAnnotations.length === 0;
Why this change? Shouldn't the annotations and sorted annotations have equal length?

2025-03-06 10:31 UTC, mzur commented on src/resources/assets/js/mixins/largoContainer.vue
> +            let cacheKey = JSON.stringify({label: label.id});
Better revert this to the previous behavior which just used the label ID as cache key. No need to stringify a whole object.

2025-03-06 10:31 UTC, mzur commented on src/resources/assets/js/mixins/largoContainer.vue
> +                Vue.set(this.annotationsCache, cacheKey, []);
Should `annotationsCache` be modified here at all? If yes, is the `cacheKey` the correct one here? Before only the label ID was used as the cache key.

2025-03-12 11:03 UTC, mzur commented
I don't have a specific style guide to recommend. In biigle/core we have an eslint check but this is not very strict (mostly to spot errors). The only advice I can give is to adhere to the existing style of the code, whatever that is worth :shrug:

2025-04-04 06:57 UTC, dbrembilla commented
@mzur I opted to disable it for now, we can add the filtering to the relabel step in a future step

2025-04-04 08:36 UTC, mzur requested changes
Almost done! I have only one real comment about how the loading of filters is implemented in JS. The remaining comments are more or less just cosmetic.

There is also another thing I noticed in the UI. If I have an active filter rule and I add another, there is a brief flash of content with all thumbnails. A similar thing happens if I have an active filter and switch to a different label. I demonstrate this in the video below. There should be no flash of content. The current state of thumbnails and the loading animation should be shown and immediately replaced with the new state once the API response is returned for the filters.

[Screencast from 2025-04-04 10-20-03.webm](https://github.com/user-attachments/assets/8d23a96e-f7a3-4f6c-b828-4e7df665ae84)

In addition, if I enable "sort by similarity" and select a reference thumbnail, then enable a filter that matches no annotation, I get the pinned thumbnail overlaid with the text:

![image](https://github.com/user-attachments/assets/e7773722-3dc5-40d1-aae0-74c5009d402e)

I think the pinned thumbnail should be hidden in this case (but still remain pinned). Maybe it is as easy as hiding the whole image grid component with `v-show` if there are no thumbnails to be shown?

2025-04-04 08:36 UTC, mzur commented on src/resources/assets/js/mixins/largoContainer.vue
> +                    .then(this.loadFilters(label, selectedFilters, union))
This is executed immediately. If you want to do it after the annotations were loaded, it has do be:

```suggestion
                    .then(() => this.loadFilters(label, selectedFilters, union))
```

But you can probably load the filters in parallel to the annotations, as it is currently done with the sorting sequence. To do this, remove the filter logic from this block of `promise1` and add a new block for `promise3` below like this:

```js
let promise3 = Promise.resolve();
if (selectedFilters.length > 0 && filtersNotInCache) {
    promise3 = this.loadFilters(...);
}

Vue.Promise.all([promise1, promise2, promise3]).finally(this.finishLoading);
```

You have to update `loadFilters()` to always return a promise then. Also see the three comments below.

2025-04-04 08:36 UTC, mzur commented on src/resources/assets/js/mixins/largoContainer.vue
> +                    .finally(this.finishLoading);
`finishLoading` is called by `Promise.all()` below.

```suggestion
```

2025-04-04 08:36 UTC, mzur commented on src/resources/assets/js/mixins/largoContainer.vue
> +                    .finally(this.finishLoading);
`startLoading` and `finishLoading` can be handled externally (see above and below).

2025-04-04 08:36 UTC, mzur commented on src/resources/assets/js/mixins/largoContainer.vue
> +            this.loadFilters(this.selectedLabel.id, filters, union);
If you choose to move the `if` checks out of `loadFilters()` because it works better in `getAnnotations()`, you maybe have to add them here, too. Also you have to add `startLoading` and `finishLoading` here, too.

2025-04-04 08:36 UTC, mzur commented on src/resources/assets/js/mixins/largoContainer.vue
> +            this.$refs.filteringTab.resetFilters();
Typically in a Vue application, the tab component would pass the information about changed filters via events to this container, which then updates the state. The state is in turn propagated via props back to the tab component, that can update the UI accordingly. If the filters should be reset, only the container has to update it's state and the tab will update automatically. Have a look at the sorting tab for an example.

All this is done to decouple the component from the parent and vice versa, so you don't have to make a hard call to a child component method as is done here.

2025-04-04 08:36 UTC, mzur commented on tests/Http/Controllers/Api/Projects/GetUsersWithAnnotationsProjectsTest.php
> +class GetUsersWithAnnotationsProjectsTest extends ApiTestCase
The test class names usually match the original classes.
```suggestion
class GetUsersWithAnnotationsTest extends ApiTestCase
```

2025-04-04 08:36 UTC, mzur commented on tests/Http/Controllers/Api/Volumes/GetUsersWithAnnotationsVolumesTest.php
> +class GetUsersWithAnnotationsVolumesTest extends ApiTestCase
```suggestion
class GetUsersWithAnnotationsTest extends ApiTestCase
```

2025-04-07 12:10 UTC, dbrembilla commented on src/resources/assets/js/mixins/largoContainer.vue
> +                    .finally(this.finishLoading);
Sorry, I don't understand here; should I resolve the Promise here like above using a `Vue.all().finally(this.finishLoading)`? I am unsure what it would change here

2025-04-07 13:24 UTC, dbrembilla commented on src/resources/assets/js/mixins/largoContainer.vue
> +                    .finally(this.finishLoading);
So, I fixed now a loading bug (sorry! I realised that this bug was there while working on the other PR), and I understood better how the other promise works. However, I still find it unclear how it would be changed here

2025-04-10 13:33 UTC, mzur reviewed
I think I found another case with flickering thumbnails but it is quite hard to reproduce. I'm quite sure I repeated the steps that caused the flickering but the second time it didn't happen...

Maybe you can have another look at possible race conditions?

2025-04-24 13:37 UTC, mzur reviewed
I found the flickering issue! Steps:

1. Add a filter rule that matches annotations of two different labels.
2. Select first one label, then the other to cache the filtered annotations.
3. Add another filter rule that still matches annotations of both labels.
4. Select the label that is currently not selected. Some patches flicker.

[Screencast from 2025-04-24 15-32-55.webm](https://github.com/user-attachments/assets/5f1e72e0-f518-4a17-9fe4-f58cf3662b41)

2025-04-24 13:37 UTC, mzur commented on src/resources/assets/js/mixins/largoContainer.vue
> +                    filterPromise = this.loadFilters(label, activeFilters, union, filtersCacheKey)
```suggestion
                    filterPromise = this.loadFilters(label, activeFilters, union, filtersCacheKey);
```

2025-04-24 13:37 UTC, mzur commented on src/resources/views/show/content.blade.php
> +                v-on:handle-selected-filters="handleSelectedFilters"
```suggestion
```

2025-04-25 07:25 UTC, mzur commented on src/resources/assets/js/components/filteringTab.vue
> +                    title="Remove this filter"
```suggestion
                    title="Remove this filter rule"
```

2025-04-25 07:27 UTC, merged