Add flat label list tab
biigle/largo pull request #194
Opened 2024-11-12 12:15 UTC by lehecht

- [ ] Add tests in VideoAnnotationTest
- [ ] Add tests in ImageAnnotationTest

Closes #170.

2024-12-06 11:06 UTC, mzur requested changes
Looks really nice! Here come the high-level comments:

- If I read the code right, you populate the tab based on a list of **all** annotations in the project/volume? This is far too inefficient. Instead, the API should return a list of *labels* only (and their number of annotations), i.e. exactly what the tab should show. You should be able to get this list with a single DB query, too. Then there also should be no need for a streamed response.

- The labels should be ordered alphabetically (like with the trees).

- The new tab should be the second from the top.

- The new tab title should be "label list".

- There is an issue with the spacing of selected labels:

  [Screencast from 06.12.2024 11:58:27.webm](https://github.com/user-attachments/assets/5eb6b30a-335e-4217-ac0c-aba6fb6e1cbb)

2024-12-13 08:17 UTC, lehecht commented
> * the API should return a list of _labels_ only (and their number of annotations)

If I return only the labels, it is not possible any more to use them later for the labels tree tab, because it needs the image's uuid and annotation id.

2024-12-18 08:25 UTC, mzur commented
But the labels for the label trees tab already come from `biigle.$require('largo.labelTrees')`, right? The new API endpoint is only there for the new flat labels tab so the endpoint can only return the information required for this tab, too.

2025-01-20 14:42 UTC, mzur commented on tests/Http/Controllers/Api/Projects/FilterImageAnnotationsByLabelControllerTest.php
> +        $content = json_decode($response->getContent())[0];
Have a look at the Laravel docs for [testing JSON APIs](https://laravel.com/docs/11.x/http-tests#testing-json-apis), this may be a little more elegant here.

2025-01-22 06:49 UTC, lehecht commented
> I get the generic error message "The server didn't respond, sorry." when I open the label list tab in Largo of a project. The API requests are sent and successful and there is no error in the console.

I cannot reproduce the error. Can you describe a little more what you used and did?

2025-01-22 09:05 UTC, mzur commented
I had a closer look and this is indeed a special case. My project has 0 label trees but still images and videos with annotations. Your code expects every annotation (label) to be present among the label trees of the project/volume. But this doesn't have to be the case. You use the computed `labelTreesIndex` to parse the API responses for the flat label list. But is this even required? The API should already provide all information that is needed for the tab. I think you don't need the `labelTreesIndex`.

2025-01-22 09:09 UTC, mzur commented on src/resources/assets/js/mixins/largoContainer.vue
> +                .catch(handleErrorResponse)
The `handleErrorResponse` can only handle API responses. Otherwise the user will only get a generic "the server did not respond" message although there is an entirely different error.

```suggestion
            Promise.all([
                AnnotationsApi.fetchImageVolumeAnnotations({ id: this.volumeId }).catch(handleErrorResponse),
                AnnotationsApi.fetchVideoVolumeAnnotations({ id: this.volumeId }).catch(handleErrorResponse)
            ])
                .then(this.parseResponse)
```

2025-01-22 09:09 UTC, mzur commented on src/resources/assets/js/projectLargoContainer.vue
> +                .catch(handleErrorResponse)
Same here:

```suggestion
            Promise.all([
                ProjectsApi.getAllProjectsImageAnnotationLabels({ id: this.projectId })
                    .catch(handleErrorResponse)
                    .then((res) => { return this.parseResponse([res, emptyResponse]) }),
                ProjectsApi.getAllProjectsVideoAnnotationLabels({ id: this.projectId })
                    .catch(handleErrorResponse)
                    .then((res) => { return this.parseResponse([emptyResponse, res]) }),
            ])
                .then(this.mergeLabels)
```

2025-01-22 09:18 UTC, lehecht commented
> The API should already provide all information that is needed for the tab

I used the labelTreesIndex to get the same objects as in the label tree. Without this, the label selection wouldn't work properly across the tabs, which could result in showing a label with wrong thumbnails. I have tried several ways, but have found no other solution. Maybe you have another idea?

2025-01-22 09:22 UTC, mzur commented
I see. You should add a comment explaining this. In this case you can ignore the label trees index if the label does not exist there, as this label can't be selected in the label trees tab anyway.

2025-01-23 07:06 UTC, lehecht commented on src/Http/Controllers/Api/Projects/FilterImageAnnotationsByLabelController.php
> +        ->get();
@mzur 
I struggle a bit with the query for the project's single API point. Here is what I got so far:

```
$videoLabelQuery = DB::table('labels')
->join('video_annotation_labels', 'labels.id', '=', 'video_annotation_labels.label_id')
->join('video_annotations', 'video_annotation_labels.annotation_id', '=', 'video_annotations.id')
->join('videos', 'video_annotations.video_id', '=', 'videos.id')
->join('project_volume', 'videos.volume_id', '=', 'project_volume.volume_id')
->where('project_volume.project_id','=',$id)
->select('labels.*');

$labelColumns = Schema::getColumnListing('labels');
$union = $videoLabelQuery->unionAll($imageLabelQuery);

return DB::query()->fromSub($union, 'labels')
->select('labels.*', DB::raw('COUNT(labels.id) as count'))
->groupBy(array_map(fn($column) => "labels.$column", $labelColumns))
->get();
```

The query works, but I think there is a better solution. `$imageLabelQuery` looks the same as `$videoLabelQuery`. Maybe you have a better idea?

2025-01-23 07:56 UTC, lehecht commented
@mzur 
> You should add a comment explaining this

[Here](https://github.com/biigle/largo/blob/0c72a2a67e95c3e08d851ab56f14616d8e98600b/src/resources/assets/js/mixins/largoContainer.vue#L540) is a comment, but maybe it's not clear enough?

2025-01-23 14:54 UTC, mzur commented
> [Here](https://github.com/biigle/largo/blob/0c72a2a67e95c3e08d851ab56f14616d8e98600b/src/resources/assets/js/mixins/largoContainer.vue#L540) is a comment, but maybe it's not clear enough?

Yeah, maybe you can elaborate the comment a bit and maybe move it to the `labelTreesIndex` method. This will explain why this index is required.

> And how can I add labels without a label tree?

For the flat label list you need the label ID, name, color and count for each label. You get all this from the API response. So if there is a label that is not present among the available label trees, you can create the label object from the API response instead.

2025-01-23 15:13 UTC, mzur commented on src/Http/Controllers/Api/Projects/FilterImageAnnotationsByLabelController.php
> +        ->get();
This looks quite fine. Sometimes queries can get verbose. The only thing I would change is to limit the select and make these columns explicit in the `groupBy()` too. This way you don't return unnecessary data from the API.

```php
$videoLabelQuery = Label::query()
   ->join('video_annotation_labels', 'labels.id', '=', 'video_annotation_labels.label_id')
   ->join('video_annotations', 'video_annotation_labels.annotation_id', '=', 'video_annotations.id')
   ->join('videos', 'video_annotations.video_id', '=', 'videos.id')
   ->join('project_volume', 'videos.volume_id', '=', 'project_volume.volume_id')
   ->where('project_volume.project_id', '=', $id)
   ->select('labels.*');

$imageLabelQuery = Label::query()
   ->join('image_annotation_labels', 'labels.id', '=', 'image_annotation_labels.label_id')
   ->join('image_annotations', 'image_annotation_labels.annotation_id', '=', 'image_annotations.id')
   ->join('images', 'image_annotations.image_id', '=', 'images.id')
   ->join('project_volume', 'images.volume_id', '=', 'project_volume.volume_id')
   ->where('project_volume.project_id', '=', $id)
   ->select('labels.*');

$union = $videoLabelQuery->unionAll($imageLabelQuery);

DB::query()->fromSub($union, 'labels')
   ->selectRaw('labels.id, labels.name, labels.color, labels.label_tree_id, count(labels.id) as count')
   ->groupBy(['labels.id', 'labels.name', 'labels.color', 'labels.label_tree_id'])
   ->get();
```

2025-01-24 08:00 UTC, lehecht commented on src/resources/assets/js/components/labelList.vue
@mzur
It is possible to use annotationsTabs and annotationsTabsLabelItem, but it's more like merging two independent classes together. I cannot really use any methods there and need to add many if-else conditions to switch between largo-mode and normal-mode. AnnotationsTabs focus' more on annotations, while my class depends more on labels.

2025-01-24 08:15 UTC, mzur commented on src/resources/assets/js/components/labelList.vue
Ok :+1:

2025-01-29 10:10 UTC, mzur requested changes
A nice improvement :+1: Two main comments:

- The labels still are not ordered alphabetically. The volume endpoint sorts them correctly but the ordering is lost in the frontend. In the project endpoint the `orderBy()` is missing, too. You should add tests for this.

- One thing I completely forgot about: Annotation sessions. If there is an annotation session that e.g. hides old annotations, these are still counted in the flat labels tab. When clicking on one of these labels, it says "no annotations exist". Adding the annotation session filter to the volume queries should be straight forward. [Here is an example](https://github.com/biigle/largo/blob/master/src/Http/Controllers/Api/Volumes/FilterImageAnnotationsByLabelController.php) (also observe the [edge case](https://github.com/biigle/largo/commit/0cb9b8eb9a575e202747a50570728b1dbd9e6532) included there). Annotation sessions are [ignored](https://github.com/biigle/largo/issues/36) in project largo so there is no need to change anything there.

2025-01-30 13:59 UTC, mzur submitted a review, later dismissed
All good, thanks! Just one `npm run prod` was missing. I also updated the Largo manual article.

2025-01-30 14:02 UTC, merged